"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Dias.fst2" Merge Disabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Horas.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Meses.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Numero.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/NumRomanos.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Valor.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Datas_Def.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Data.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Tempo.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Preposicao.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Coisa.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/LocalSigarra.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Acontecimento.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Outro.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Obra.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/palavrasMinusculasFamilia.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/ReconheceRelacaoFamiliar.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Abstraccao.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Local.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Relacao-LocalNascimento.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Relacao-Inclui-Local.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Enumeracao.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/palavrasMinusculasHarem.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/1-ReconheceNomesCompostos.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/2-Reconhece2NomesProprios.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/11-ReconheceNomesLeNer.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/3-ReconheceAcoesHumAEsquerda.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/4-ReconhecePronomesDeTratamento.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/5-ReconheceAcoesHumADireita.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/6-ReconheceAposto.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/7-ReconheceMinusculasHAREMAEsquerda.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/8-ReconheceContextoAEsquerda.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/8-ReconhecePerguntasComNomes.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/9-AcaoRealizadaPor.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/10-ReconheceNomeSucedidoPorIdade.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Organizacao.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/12-ReconheceNomeSemContexto.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Enumeracao.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Relacoes-Paternidade-Biblia.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Paralelismo.fst2" Merge Enabled 1 0
"../../../../../Documentos/UFES/TCC/TCC-2/AvaliadorRelacoes/Grafos/Relacao-Ocorre_Em.fst2" Merge Enabled 1 0
